### ISSUE TITLE
coursier SBT plugin messes with Logback logging

### ISSUE THREAD

**Issue by velvia** [alexarchambault/coursier#149]
I have a project (github.com/tuplejump/FiloDB) that uses logback for test logs.  I only enable WARN or higher log levels to stdout, and the rest go out to a file.  When I enable Coursier SBT plugin (1.0.0-M8), the logging level that gets sent out to STDOUT becomes INFO, which totally clutters up my screen.

**Comment by velvia** [comment]
To reproduce:
0. Add coursier to ~/.sbt/0.13/plugins/plugins.sbt etc.   (1.0.0-M8)
1. clone https://github.com/tuplejump/FiloDB
2. sbt spark/test; you will see lots of INFO output.  If you disable coursier you will only see WARN output.

**Comment by alexarchambault** [comment]
I fixed that on [my fork](https://github.com/alexarchambault/FiloDB/tree/topic/exclude-slf4j) of FiloDB.

The first error (the one you raise) originates from both `slf4j-log4j12` and `logback-classic` to land in the classpath, both *with and without* the coursier SBT plugin. The error is less visible without the coursier SBT plugin, as `logback-classic` gets chosen among the two, hence the right logging behavior it seems. The log messages of `spark/test` say:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/user/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.7.jar!/o
rg/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/user/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.10.jar!/org/slf4j
/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```
With the coursier SBT plugin, the other one gets chosen, hence more logs.

It should be fixed directly in FiloDB imo, by excluding `slf4j-log4j12`, like done at https://github.com/alexarchambault/FiloDB/commit/4f1c27e792a9b989ee2e82dacc61c674e4fd3400.

**Comment by alexarchambault** [comment]
Once this is addressed, a second issue arises, because of `org.jboss.netty:netty` landing in the classpath with the coursier SBT plugin enabled. I discuss that in the [upcoming FAQ](https://github.com/alexarchambault/coursier/tree/3c32ec4c2f30999ec45a5b9fb3e492e5d32f8876#with-spark--15-i-get-some-noverifyerror-exceptions-related-to-jbossnetty-why). It can be addressed by excluding it from the spark dependencies, like quickly done at https://github.com/alexarchambault/FiloDB/commit/0d6a42cc8d9da4fa9a7cb8964e1924846f90545e. (As a side note, I'd prefer other eyes to have a look at that before asking spark to add an exclusion targetting it.)

**Comment by velvia** [comment]
@alexarchambault Thanks so much for the investigation.  Fixed it on my side.
