### ISSUE TITLE
Classifiers issue

### ISSUE THREAD

**Issue by cheleb** [alexarchambault/coursier#298]
This project
https://github.com/druid-io/tranquility/
 fails with:

> [error] 2 not found
> [error]   https://repo1.maven.org/maven2/org/apache/flink/flink-core/1.0.3/flink-core-1.0.3.test-jar
> [error]   https://repo1.maven.org/maven2/org/apache/flink/flink-runtime_2.10/1.0.3/flink-runtime_2.10-1.0.3.test-jar

 when resolving artifacts with "tests" classifiers.

My intuition in that, the token "test-jar" if deduced from the pom file ... my less than 2 cents.

net.virtualvoid.sbt.graph.Plugin.graphSettings must be changed to net.virtualvoid.sbt.graph.DependencyGraphSettings.graphSettings

PS. The project build without coursier.

**Comment by matt-martin** [comment]
Running into a similar issue where the artifact type seems to be set to test-jar in the pom.  For example, the pom for [hadoop-yarn-server-resourcemanager-2.7.1](http://central.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.7.1/hadoop-yarn-server-resourcemanager-2.7.1.pom) has dependencies like:

{code}
<dependency>
    <groupId>org.apache.zookeeper</groupId>
    <artifactId>zookeeper</artifactId>
    <type>test-jar</type>
</dependency>
{code}


There seems to be some description of these "default" types (and there associated artifact handlers) here:

https://github.com/apache/maven/blob/c023e58104b71e27def0caa034d39ab0fa0373b6/maven-core/src/site/apt/artifact-handlers.apt

I've also put together a barebones SBT project to help illustrate this issue here: https://github.com/matt-martin/coursier-zoo-test

**Comment by matt-martin** [comment]
I think the following map needs to be updated to include the `test-jar` key:

https://github.com/alexarchambault/coursier/blob/c5fb28f982ff03eef386958f79954b846187acd7/core/shared/src/main/scala/coursier/maven/MavenSource.scala#L157

And probably some changes to the `artifacts` method above that to select the appropriate classifier, etc based on the artifact type.
